kind: PersistentVolume
apiVersion: v1
metadata:
  name: aca
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: aaa
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: aba
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"
