apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  completions: 60
  parallelism: 2
  template:
    spec:
      containers:
      - image: perl
        name: pi
        resources: {}
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
status: {}
